# Generated by Django 3.2.12 on 2022-04-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0006_auto_20220413_1359'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_name'], name='product_idx'),
        ),
    ]
