# Generated by Django 3.2.12 on 2022-04-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0007_product_product_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_name'], name='category_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['image'], name='image_category_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['product'], name='product_image_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['image'], name='image_product_idx'),
        ),
    ]
