# Generated by Django 3.2.12 on 2022-04-26 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0009_auto_20220421_1412'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_idx',
        ),
    ]
